# Generated by Django 5.0.1 on 2024-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trabajador_dni_alter_trabajador_periocidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tipodoc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('Carnet de Extranjería', 'Carnet de Extranjería')], max_length=26),
        ),
    ]
