# Generated by Django 5.0.1 on 2024-01-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trabajador_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuarioapp',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Garita', 'Garita'), ('Proceso Pota', 'Proceso Pota'), ('Proceso Merluza', 'Proceso Merluza')], default='Garita', max_length=25),
        ),
    ]
