# Generated by Django 5.0.1 on 2024-01-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_especie_eleccionespecie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eleccionespecie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eleccionespecie',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='eleccionespecie',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='EleccionEspecie',
        ),
    ]
