# Generated by Django 5.0.1 on 2024-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_grupo_merluza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_MERLUZA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
    ]
