# Generated by Django 5.0.1 on 2024-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_actividad_merluza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion_MERLUZA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=100)),
            ],
        ),
    ]
