# Generated by Django 5.0.1 on 2024-01-31 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_actividad_pota_grupo_pota_presentacion_pota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('apel_nomb', models.CharField(blank=True, max_length=1020)),
                ('trabajador_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajador')),
            ],
        ),
    ]
