# Generated by Django 5.0.1 on 2024-01-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
