# Generated by Django 5.0.1 on 2024-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_trabajosrealizados_trabajador_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosrealizados',
            name='Ndocumento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
