# Generated by Django 5.0.1 on 2024-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_trabajosrealizados_ndocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosrealizados',
            name='creado_por',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
