# Generated by Django 5.0.1 on 2024-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_trabajosrealizados_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosrealizados',
            name='kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
