# Generated by Django 5.0.1 on 2024-02-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_trabajosrealizados_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajosrealizados',
            old_name='creado_por',
            new_name='creado_por_user',
        ),
    ]
